#!/usr/bin/env ruby

require_relative('lib/utils.rb')

CONVERSION_MAP = [
  ['.', 'O', '\'', '/', '3', '8', ';', ']', 'X' ],
  ['.', 'B', '+', '*', '#', 'T', 'P', '$', 'X' ],
]

def convert(string)
  character_map(string, CONVERSION_MAP)
end

do_work(ARGV, method(:convert))
